name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Antq
        uses: ./
        with:
          excludes: 'foo bar actions/checkout'
